apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: my-first-project
  description: My first Backstage integrated project 🚀
  tags:
    - nodejs
    - backend

spec:
  type: service
  owner: user:guest
  lifecycle: experimental
