apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-first-project
  description: AI-powered CCTV monitoring backend 🚀
  annotations:
    github.com/project-slug: amanraghav1928-code/my-first-project
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - ai
    - cctv
    - backend

spec:
  type: service
  owner: user:guest
  lifecycle: experimental

  providesApis:
    - cctv-api

  dependsOn:
    - resource:default/cctv-database
